site_name: 'Razo Ranch: The Games'

extra:
  homepage: https://thegamesseason4.github.io/

theme:
  favicon: images/favicon.ico
  logo: images/favicon.ico
  features:
    - navigation.top
    - toc.integrate
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home Page: index.md
  - Previous Activities:
      - Paintball Wars: previous_activities/paintball_wars.md
      - Obstacle Course: previous_activities/obstacle_course.md
      - Season 1: previous_activities/season_one.md
      - Season 2: previous_activities/season_two.md
      - Season 3: previous_activities/season_three.md
