site_name: 'Razo Ranch: The Games'

extra:
  homepage: https://thegamesseason4.github.io/

theme:
  features:
    - navigation.top
    - toc.integrate
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home Page: index.md
  - Previous Seasons:
      - Season 1: previous_season/season_one.md
      - Season 2: previous_season/season_two.md
      - Season 3: previous_season/season_three.md
